[2022-08-29 16:00:14,596] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2022-08-28T00:00:00+00:00 [queued]>
[2022-08-29 16:00:14,613] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2022-08-28T00:00:00+00:00 [queued]>
[2022-08-29 16:00:14,613] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 16:00:14,613] {taskinstance.py:1357} INFO - Starting attempt 3 of 3
[2022-08-29 16:00:14,613] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 16:00:14,662] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2022-08-28 00:00:00+00:00
[2022-08-29 16:00:14,678] {standard_task_runner.py:52} INFO - Started process 2399 to run task
[2022-08-29 16:00:14,693] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'scheduled__2022-08-28T00:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp5demeaok', '--error-file', '/tmp/tmp4c373dga']
[2022-08-29 16:00:14,703] {standard_task_runner.py:80} INFO - Job 97: Subtask store_user
[2022-08-29 16:00:14,866] {task_command.py:369} INFO - Running <TaskInstance: user_processing.store_user scheduled__2022-08-28T00:00:00+00:00 [running]> on host 7f0ff65cfbf7
[2022-08-29 16:00:15,027] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2022-08-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-28T00:00:00+00:00
[2022-08-29 16:00:15,029] {postgres.py:127} INFO - Running copy expert: COPY users from stdin WITH DELIMITER AS ',', filename: /tmp/processed_user.csv
[2022-08-29 16:00:15,043] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-29 16:00:15,051] {python.py:173} INFO - Done. Returned value was: None
[2022-08-29 16:00:15,074] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, execution_date=20220828T000000, start_date=20220829T160014, end_date=20220829T160015
[2022-08-29 16:00:15,120] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-29 16:00:15,187] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
